### ISSUE TITLE
Feature Request: shiftFocusTo or findAndShiftFocus

### ISSUE THREAD

**Issue by andys8** [JordanMartinez/purescript-arrays-zipper#1]
Hi @JordanMartinez , I'm trying this zipper library.

I'm looking for a more convenient way to change the focused item. My use case is a list of tab buttons, where each one can be selected.

Here are some ideas. I'm very open to changing names, types, returning a `Maybe` or avoid these, if there is already an easy way using `Traversable`/`Foldable`.

I can also provide a pull request, when details were discussed.

## Ideas

```purescript
shiftFocusTo :: forall a. Eq a => a -> ArrayZipper a -> ArrayZipper a
shiftFocusTo a zipper = fromMaybe zipper maybeZipper
  where
  maybeZipper = do
    index <- findIndex ((==) a) $ exposeArray zipper
    pure $ shiftFocusBy (const index) zipper


findAndShiftFocus :: forall a. (a -> Boolean) -> ArrayZipper a -> ArrayZipper a
findAndShiftFocus f zipper = fromMaybe zipper maybeZipper
  where
  maybeZipper = do
    index <- findIndex f $ exposeArray zipper
    pure $ shiftFocusBy (const index) zipper
```

## Other libraries

 `wernerdegroot/listzipper` provides:

```
find : (a -> Bool) -> Zipper a -> Maybe (Zipper a)
findFirst : (a -> Bool) -> Zipper a -> Maybe (Zipper a)
```

https://package.elm-lang.org/packages/wernerdegroot/listzipper/latest/List-Zipper#find

**Comment by JordanMartinez** [comment]
That makes sense.

I'll accept a PR for both functions. However, I think the `shiftFocusTo` should include a `shiftFocusTo'` variant that returns a `Maybe (ArrayZipper a)`. When the index is out-of-bounds, it'll return `Nothing`. 

I also think the `findAndShiftFocus` function name should match the other `shiftFocus*` functions. Perhaps `shiftFocusByFind`?

Lastly, since `findIndex` already returns back a valid index into the array, we can just rebuild the zipper using that index directly. There's no reason to use `shiftFocusBy`:
```purescript
findAndShiftFocus :: forall a. (a -> Boolean) -> ArrayZipper a -> ArrayZipper a
findAndShiftFocus f zipper@(ArrayZipper r) = fromMaybe zipper maybeZipper
  where
  maybeZipper = do
    index <- findIndex f r.array
    pure $ ArrayZipper $ r { focusIndex = index }
```

**Comment by andys8** [comment]
I created a PR #2 to add all 4 functions and tests
